export {
  isBenchmarkResultView,
  isImportedResultView,
  isWorkQueueView,
  parseResultViewRecords,
} from './generated/resultViewRecords.ts';

export type {
  BenchmarkResultRecord,
  BenchmarkResultViewRecord,
  CompetencePointRecord,
  CostAxisRecord,
  CostSummaryRecord,
  ImportedPublicationBundleRecord,
  ImportedResultViewRecord,
  ModelResultRecord,
  ProposalRecord,
  ResultViewRecord,
  RunDetailEntryRecord,
  RunDetailSectionRecord,
  RunDetailTableRecord,
  RunDetailViewModelRecord,
  RunResultRecord,
  TrainingArtifactReferenceRecord,
  TrainingDiagnosticsRecord,
  TrainingHistoryPointRecord,
  TrainingProtocolRecord,
  WorkQueueItemRecord,
  WorkQueueItemStatus,
  WorkQueueViewRecord,
} from './generated/resultViewRecords.ts';
